server:
   servlet:
      contextPath: /con-refund-inq-manager
db:
  con:
    url: jdbc:oracle:thin:@//172.20.186.125:1521/SSODB
    username: SSOCONSCM
    password: Pa55w0rd
redis:
  cluster:
    hosts:
      172.20.185.20:6479,
      172.20.185.21:6480,
      172.20.185.22:6480
    
#logging:
#  level:
#    root: DEBUG
logging:
  level:
    root: ERROR
    th.go.sso.newcore.cont.refund.inquiry.business: DEBUG
    th.go.sso.newcore.cont.refund.inquiry.ws.provider: DEBUG