server:
   servlet:
      contextPath: /refund-inq
db:
  con:
    url: jdbc:oracle:thin:@//103.113.178.149:1522/SSODB
    username: SSOCONSCM
    password: Pa55w0rd
redis:
  #hostName: 103.113.178.149
  #port: 6379
  #password: SS0r3dis
  hostName: 159.223.70.139
  port: 8000
  password: c0nRedisPwd
logging:
  level:
    root: ERROR
    th.go.sso.newcore.cont.refund.inquiry.business: DEBUG
    th.go.sso.newcore.cont.refund.inquiry.ws.provider: DEBUG
    th.go.sso.newcore.cont.refund.inquiry.config: DEBUG
    th.go.sso.newcore.cont.refund.inquiry.listener: DEBUG