apiVersion: apps/v1
kind: Deployment
metadata:
  name: APPNAME-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: APPNAME
  template:
    metadata:
      labels:
        app: APPNAME
    spec:
      containers:
        - name: APPNAME
          image: DEPLOYMENTIMAGE
          ports:
            - containerPort: PORT
      imagePullSecrets:
        - name: gitlab-auth
---
apiVersion: v1
kind: Service
metadata:
  name: APPNAME-service
spec:
  type: ClusterIP
  selector:
    app: APPNAME
  ports:
    - port: PORT
      protocol: TCP
      targetPort: PORT
